# Source: jxboot-helmfile-resources/templates/ingress-config-configmap.yaml
apiVersion: v1
data:
  domain: "a09c21669d85040a695cb9389b018565-211d617c41622717.elb.us-east-1.amazonaws.com"
  email: ""
  exposer: "Ingress"
  issuer: ""
  tls: "false"
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
